apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: client-intents-for-server
  namespace: otterize-tutorial-npol
spec:
  service:
    name: server
  calls:
    - name: "client"
